### ISSUE TITLE
ワードのいいね数に応じたソートの挙動

### ISSUE THREAD

**Issue by KeitaIsFree** [enpitut2021/nanashi_no_ikkaku#9]
ソートの仕様上、いいね数が同じワードの画面上の順番がデータベース上の順番によって決まっている。なので、一個上のワードといいね数が同じになったときに、順番が上と入れ替わる場合と入れ替わらない場合がある。（適当にどれかのワードで試してみるとわかると思います。）細かいことなので優先順位は低い。

**Comment by Mattun1212** [comment]
データ追加時にdocument名を指定できるはずなのでそこで整理できはするはず
今後いいねの順番にかかわらず整理される必要がありそうなら実装すれば良いかと思った

**Comment by KeitaIsFree** [comment]
お互い違うことの話をしてる気がするので授業の時話しましょー
